#!/usr/bin/env node
// Reads .env from repo root → writes js/config.js (gitignored)
// Usage: node scripts/gen_config.js
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const env  = resolve(root, '.env');
const out  = resolve(root, 'js', 'config.js');

const vars = {};
try {
  readFileSync(env, 'utf8').split('\n').forEach(line => {
    const m = line.match(/^([A-Z_]+)\s*=\s*(.+)$/);
    if (m) vars[m[1]] = m[2].trim().replace(/^['"]|['"]$/g, '');
  });
} catch {
  console.error('Cannot read .env — file missing?');
  process.exit(1);
}

const key   = vars['CLAUDE_API_KEY'] || vars['ANTHROPIC_API_KEY'] || '';
const model = vars['CLAUDE_MODEL'] || 'claude-sonnet-4-6';

if (!key) { console.error('No CLAUDE_API_KEY or ANTHROPIC_API_KEY in .env'); process.exit(1); }

writeFileSync(out, `// Auto-generated by scripts/gen_config.js — DO NOT COMMIT
export const CLAUDE_KEY   = '${key}';
export const CLAUDE_MODEL = '${model}';
`);
console.log(`✓ js/config.js generated (key: ${key.slice(0,12)}…, model: ${model})`);
